# Generated by Django 6.0.3 on 2026-03-17 07:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Customer full name",
                        max_length=200,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Primary contact number",
                        max_length=20,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True,
                        help_text="Alternative contact number",
                        max_length=20,
                        verbose_name="Secondary Phone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Address"
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Customer address for records",
                        verbose_name="Address",
                    ),
                ),
                (
                    "service_preferences",
                    models.TextField(
                        blank=True,
                        help_text="Customer preferences and special requirements",
                        verbose_name="Service Preferences",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this customer",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "total_visits",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times customer has used services",
                        verbose_name="Total Visits",
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount spent by customer",
                        max_digits=12,
                        verbose_name="Total Spent (KES)",
                    ),
                ),
                (
                    "is_vip",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as VIP for priority service",
                        verbose_name="VIP Customer",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive customers are hidden from search",
                        verbose_name="Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        help_text="Vehicle registration plate number",
                        max_length=20,
                        unique=True,
                        verbose_name="Plate Number",
                    ),
                ),
                (
                    "make",
                    models.CharField(
                        help_text="Vehicle manufacturer (e.g., Toyota, Honda)",
                        max_length=50,
                        verbose_name="Make",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Vehicle model (e.g., Corolla, Civic)",
                        max_length=50,
                        verbose_name="Model",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Year of manufacture",
                        null=True,
                        verbose_name="Year",
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=30, verbose_name="Color"),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("sedan", "Sedan"),
                            ("suv", "SUV"),
                            ("hatchback", "Hatchback"),
                            ("pickup", "Pickup/Truck"),
                            ("van", "Van/Minibus"),
                            ("motorcycle", "Motorcycle"),
                            ("other", "Other"),
                        ],
                        default="sedan",
                        max_length=20,
                        verbose_name="Vehicle Type",
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Current odometer reading",
                        null=True,
                        verbose_name="Mileage (km)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Special notes about this vehicle",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive vehicles are hidden from search",
                        verbose_name="Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="customers.customer",
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "ordering": ["-created_at"],
            },
        ),
    ]
