# Generated by Django 6.0.3 on 2026-03-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('sports_car', 'Sports Car'), ('sedan', 'Sedan'), ('luxury_car', 'Luxury Car'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup/Truck'), ('electric_car', 'Electric Car'), ('van', 'Van/Minibus'), ('motorcycle', 'Motorcycle'), ('other', 'Other')], default='sedan', max_length=20, verbose_name='Vehicle Type'),
        ),
    ]
