# Generated by Django 6.0.3 on 2026-03-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("worker", "Worker"),
                    ("customer", "Customer"),
                ],
                default="worker",
                help_text="User role determines access permissions",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
