# Generated by Django 6.0.3 on 2026-03-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Optional — customers can leave blank', verbose_name='Address'),
        ),
    ]
