# Generated by Django 6.0.3 on 2026-03-17 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("jobs", "0001_initial"),
        ("services", "0001_initial"),
        ("workers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="assigned_worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_jobs",
                to="workers.workerprofile",
                verbose_name="Assigned Worker",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_jobs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="customers.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="customers.vehicle",
                verbose_name="Vehicle",
            ),
        ),
        migrations.AddField(
            model_name="jobservice",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_services",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Completed By",
            ),
        ),
        migrations.AddField(
            model_name="jobservice",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.job",
                verbose_name="Job",
            ),
        ),
        migrations.AddField(
            model_name="jobservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="services.service",
                verbose_name="Service",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="services",
            field=models.ManyToManyField(
                related_name="jobs",
                through="jobs.JobService",
                to="services.service",
                verbose_name="Services",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobservice",
            unique_together={("job", "service")},
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "created_at"], name="jobs_job_status_277b31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["assigned_worker", "status"], name="jobs_job_assigne_9dc58b_idx"
            ),
        ),
    ]
