# Generated by Django 6.0.3 on 2026-03-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='mpesa_phone',
            field=models.CharField(blank=True, help_text='Phone used for the last M-Pesa payment', max_length=20, verbose_name='M-Pesa phone'),
        ),
        migrations.AddField(
            model_name='job',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, help_text='MPESA transaction code or reference', max_length=64, verbose_name='M-Pesa confirmation'),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_channel',
            field=models.CharField(choices=[('unspecified', 'Not set'), ('mpesa', 'M-Pesa'), ('cash', 'Cash')], default='unspecified', help_text='M-Pesa when customer pays online; cash when manager records payment', max_length=20, verbose_name='Payment channel'),
        ),
    ]
