# Generated by Django 6.0.3 on 2026-03-23 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_payment_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaStkInitiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_desc', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_stk_requests', to='jobs.job')),
            ],
            options={
                'verbose_name': 'M-Pesa STK initiation',
                'verbose_name_plural': 'M-Pesa STK initiations',
                'ordering': ['-created_at'],
            },
        ),
    ]
