# Generated by Django 6.0.3 on 2026-03-17 07:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the service",
                        max_length=100,
                        verbose_name="Service Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the service",
                        verbose_name="Description",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Service"),
                            ("extra", "Extra Service"),
                        ],
                        default="basic",
                        help_text="Basic services are standard, Extra services are add-ons",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Service price in Kenyan Shillings",
                        max_digits=10,
                        verbose_name="Price (KES)",
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Estimated time to complete the service",
                        verbose_name="Estimated Duration (minutes)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive services are not available for new jobs",
                        verbose_name="Active",
                    ),
                ),
                (
                    "requires_special_equipment",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this service needs special tools or equipment",
                        verbose_name="Requires Special Equipment",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which service appears in lists",
                        verbose_name="Display Order",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["display_order", "category", "name"],
            },
        ),
    ]
