# Generated by Django 6.0.3 on 2026-03-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.CharField(
                choices=[
                    ("exterior", "Exterior"),
                    ("interior", "Interior"),
                    ("detailing", "Detailing"),
                    ("additional", "Additional Services"),
                ],
                default="exterior",
                help_text="Service category",
                max_length=20,
                verbose_name="Category",
            ),
        ),
    ]
