# Generated by Django 6.0.3 on 2026-03-17 07:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Whether worker is available for job assignment",
                        verbose_name="Available",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average rating from 0 to 5",
                        max_digits=3,
                        verbose_name="Average Rating",
                    ),
                ),
                (
                    "total_ratings",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of ratings received",
                        verbose_name="Total Ratings",
                    ),
                ),
                (
                    "total_jobs_completed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of jobs completed",
                        verbose_name="Jobs Completed",
                    ),
                ),
                (
                    "average_completion_time",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Average time to complete a job",
                        verbose_name="Avg Completion Time (minutes)",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        help_text="Internal employee identifier",
                        max_length=20,
                        verbose_name="Employee ID",
                    ),
                ),
                (
                    "hired_date",
                    models.DateField(blank=True, null=True, verbose_name="Date Hired"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this worker",
                        verbose_name="Notes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Job the worker is currently working on",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_worker_set",
                        to="jobs.job",
                        verbose_name="Current Job",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Services this worker can perform",
                        related_name="skilled_workers",
                        to="services.service",
                        verbose_name="Skills",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker Profile",
                "verbose_name_plural": "Worker Profiles",
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
    ]
